apiVersion: v1
kind: Secret
metadata:
  name: {{ include "titanic.fullname" . }}-secrets
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  DB_NAME: {{ .Values.env.db.name }}
  POSTGRES_USER: {{ .Values.secrets.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword }}
  POSTGRES_DB: {{ .Values.env.db.name }}