apiVersion: v1
kind: Secret
metadata:
  name: titanic-secrets
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: supersecret
  POSTGRES_DB: titanic

  # API still needs these
  DB_USER: admin
  DB_PASSWORD: supersecret
  DB_NAME: titanic




# apiVersion: v1
# kind: Secret
# metadata:
#   name: titanic-secrets
# type: Opaque
# stringData:
#   DB_USER: admin
#   DB_PASSWORD: supersecret